
const ERROR = require('../errors/error');
const validarEmail = require('./validarEmail');

function validarFormularioRegistro(formularioBodyJSON) {
    const {email, password, passwordRepetido} = formularioBodyJSON;
    const errores = {};

    if(!validarEmail(email)) errores.email = ERROR.es.EMAIL_INCORRECTO;

    console.log(email, password, passwordRepetido);
    console.log(errores);
    return true;
}

module.exports = validarFormularioRegistro;

/*
Validacion de campos de formulario:
- Email
    - email format
    - only allow domains: google.
    - email not registered already.
- Password
    - From 6-20 characters long.
    - At least 1 special character. From:
    - At least 1 number.
    - At least 1 capital letter.
- PasswordConfirm
    - Same as original.
- (Username autogenerated via API).
- _csrf
    - confirm token.

*/