
const ERROR = require('../messages/errors/error');
const validarEmail = require('./validarEmail');
const validarPassword = require('./validarPassword');

function validarFormularioRegistro(req) {
    const {email, password, passwordRepetido} = req.body;
    const errores = {};

    if(!validarEmail(email)) errores.email = ERROR.es.EMAIL_INCORRECTO;
    if(!validarPassword(password)) errores.password = ERROR.es.PASSWORD_FORMATO_INCORRECTO;
    if(password !== passwordRepetido) errores.passwordRepetido = ERROR.es.PASSWORDS_NO_COINCIDEN;

    if(Object.keys(errores).length > 0) {
        req.errores = {
            error: ERROR.es.FORMULARIO_INCORRECTO,
            detalles: errores
        }
        return false;
    }

    return true;
}

module.exports = validarFormularioRegistro;

/*
Validacion de campos de formulario:
- Email
    - email format
    - only allow domains: google.
    - email not registered already.
- Password
    - From 6-20 characters long.
    - At least 1 special character. From:
    - At least 1 number.
    - At least 1 capital letter.
- PasswordConfirm
    - Same as original.
- (Username autogenerated via API).
- _csrf
    - confirm token.

*/