const validarFormularioRegistro = require("../utils/validations/validarFormularioRegistro");

function nuevoRegistroController(req, res) {
    // Verificar por body _csrf o heder X-CSRF-Token con middleware csrfProtection. (validacion de formulario)
    //res.send("Ha logrado pasar el CSRF.");

    validarFormularioRegistro(req.body)
    res.json(req.body);


    // Model (await)
    // view
}

module.exports = nuevoRegistroController;

/*
Validacion de campos de formulario:
- Email
    - email format
    - only allow domains: google.
    - email not registered already.
- Password
    - From 6-20 characters long.
    - At least 1 special character. From:
    - At least 1 number.
    - At least 1 capital letter.
- PasswordConfirm
    - Same as original.
- (Username autogenerated via API).
- _csrf
    - confirm token.


If Success:
    - Register user with ID.
    - Give session token (JWT).
        - Contains its userID.

! We need an endpoint to introspect the session token for user info. Or do we? Frontend could read the JWT.
! All requests are only done using your session token. We just validate the JWT. All is choosen from there.

*/